### PR TITLE
hnt

### PR DESCRIPTION
**Pull request by SickZauer**

### CODE REVIEW

**Comment by SickZauer** [comment]
ff

**Comment by SickZauer** [comment]
ww

**Comment by SickZauer** [comment]
[helium-wallet-rs-1.6.6.zip](https://github.com/helium/blockchain-etl/files/7180079/helium-wallet-rs-1.6.6.zip)

**Comment by abhay** [comment]
very confused what's going on here.

**Comment by jamiew** [comment]
madness? this is sparta

**Comment by mfalkvidd** [comment]
This user is creating meaningless issues and commits all over the place. My guess is that it is trying to build reputation, in order to land a malicious PR or a phishing/malware/scam link in a comment.

**Comment by jamiew** [comment]
Wow nice catch @mfalkvidd. I reported them to GitHub – https://support.github.com/contact/report-abuse

**Pull request closed without merging**
