### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by jamiew**
- Expand setup instructions and move to top
- Fix incorrect markdown 
- Hi Marc

### CODE REVIEW

**Comment by jamiew** [comment]
I'm running postgres 10. I believe 11 works too. @rawrmaan did you say you ran into issues running on postgres 12?

And do we require any particular rust minimum version?

**Comment by madninja** [comment]
I think we need to fix #138 and adjust the GOOGLE api key  instructions?

**Comment by jamiew** [comment]
@madninja I pretended like that is fixed already and the key is optional

**Comment by stephendrobinson** [comment]
I'm currently trying to install on..
 - linode
 - ubuntu 20
 - postgres 12 (latest version at this time)

Feedback points:
1) README wasn't clear that I needed to rename .env.dev to .env (otherwise the make start failed)
2) Also that postgres seemed to need postgis installed, as per 
sudo apt-get install postgis
(might want to add a short section on installing postgres including a mention to mapping to a spare volume as the blockchain grows - I was told it could be 200GB - hence I created a 512G drive for this)

**Comment by madninja** [comment]
Did https://github.com/helium/blockchain-etl/pull/141 address these? @jamiew makes his PRs confusing

**Comment by stephendrobinson** [comment]
#141 addresses all the issues - thanks!

**Comment by jamiew** [comment]
Sweet. FYI I'm up to about 400GB of space utilized for postgres (version
10), and that is recently VACUUM'd

Up to about 35GB for blockchain ledger data

**Comment by madninja** [comment]
> Sweet. FYI I'm up to about 400GB of space utilized for postgres (version 10), and that is recently VACUUM'd Up to about 35GB for blockchain ledger data

Quite unrelated to this issue, but I hear ya

**Comment by jamiew** [comment]
@madninja README still out of date without this PR

**Comment by madninja** [comment]
> @madninja README still out of date without this PR

does it need fixes based on the other PR? hard to track given all the noise today

**Comment by madninja** [comment]
no it does not.. looks good

**Comment by jamiew** [comment]
No, each PR is self-contained

**Pull request merged**
